#!/bin/sh

if ! command -v npm >/dev/null 2>&1 && [ -s "$HOME/.nvm/nvm.sh" ]; then
  . "$HOME/.nvm/nvm.sh"
  nvm use
fi

# Run tests before pushing
npm run test:full
if [ $? -ne 0 ]; then
  echo "Tests failed; aborting push."
  exit 1
fi
